# Generated by Django 5.2.6 on 2025-11-05 10:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_units", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OverheadCostContainer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Например: 'Накладные расходы Q1 2025' или 'Стандартные НР'",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Дополнительная информация о составе накладных расходов",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "materials_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("30.00"),
                        help_text="Процент накладных расходов, распределяемый на материалы (0-100)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="% на материалы",
                    ),
                ),
                (
                    "works_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("70.00"),
                        help_text="Процент накладных расходов, распределяемый на работы (0-100)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="% на работы",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Неактивные контейнеры не доступны для применения к сметам",
                        verbose_name="Активен",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
            ],
            options={
                "verbose_name": "Контейнер накладных расходов",
                "verbose_name_plural": "Контейнеры накладных расходов",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OverheadCostItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Например: 'НДС 20%', 'Зарплата администрации', 'Аренда офиса'",
                        max_length=255,
                        verbose_name="Наименование статьи",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("1.000"),
                        max_digits=16,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                        verbose_name="Количество",
                    ),
                ),
                (
                    "price_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Цена за единицу",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Дополнительная информация о статье расходов",
                        verbose_name="Комментарий",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Порядок отображения статей в контейнере",
                        verbose_name="Порядок",
                    ),
                ),
                (
                    "container",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="app_overhead_costs.overheadcostcontainer",
                        verbose_name="Контейнер",
                    ),
                ),
                (
                    "unit_ref",
                    models.ForeignKey(
                        help_text="Выберите из справочника",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="overheadcostitems",
                        to="app_units.unit",
                        verbose_name="Единица измерения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статья накладных расходов",
                "verbose_name_plural": "Статьи накладных расходов",
                "ordering": ["order", "id"],
            },
        ),
    ]
