# Generated by Django 5.2.6 on 2025-10-22 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_overhead_costs", "0001_initial"),
        ("app_units", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="overheadcostitem",
            name="unit",
        ),
        migrations.AddField(
            model_name="overheadcostitem",
            name="unit_ref",
            field=models.ForeignKey(
                default=1,
                help_text="Выбирите из справочника",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="overheadcostitems",
                to="app_units.unit",
                verbose_name="Единица измерения",
            ),
            preserve_default=False,
        ),
    ]
