# Generated by Django 5.2.6 on 2025-10-23 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_overhead_costs", "0002_remove_overheadcostitem_unit_and_more"),
        ("app_units", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="overheadcostitem",
            name="unit_ref",
            field=models.ForeignKey(
                help_text="Выберите из справочника",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="overheadcostitems",
                to="app_units.unit",
                verbose_name="Единица измерения",
            ),
        ),
    ]
