# Generated by Django 5.2.6 on 2025-11-05 10:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_suppliers", "0001_initial"),
        ("app_units", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Короткое понятное название материала.",
                        max_length=255,
                        verbose_name="Наименование",
                    ),
                ),
                (
                    "price_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Текущая цена за 1 единицу измерения (живой справочник).",
                        max_digits=12,
                        verbose_name="Цена за единицу (без НДС)",
                    ),
                ),
                (
                    "vat_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Ставка НДС в процентах, например 12.00; оставьте пустым, если не задано.",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="НДС, %",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Снимите отметку, чтобы скрыть материал из выбора без удаления.",
                        verbose_name="Активен",
                    ),
                ),
                (
                    "supplier_ref",
                    models.ForeignKey(
                        blank=True,
                        help_text="Справочник поставщиков.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="materials",
                        to="app_suppliers.supplier",
                        verbose_name="Поставщик",
                    ),
                ),
                (
                    "unit_ref",
                    models.ForeignKey(
                        help_text="Выберите из справочника",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="materials",
                        to="app_units.unit",
                        verbose_name="Единица измерения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Материал",
                "verbose_name_plural": "Материалы",
                "ordering": ["name", "id"],
            },
        ),
    ]
