# Generated by Django 5.2.6 on 2025-10-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_materials", "0002_material_code_material_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="material",
            name="code",
        ),
        migrations.AlterField(
            model_name="material",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Снимите отметку, чтобы скрыть материал из выбора без удаления.",
                verbose_name="Активен",
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="Короткое понятное название материала.",
                max_length=255,
                verbose_name="Наименование",
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="price_per_unit",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                help_text="Текущая цена за 1 единицу измерения (живой справочник).",
                max_digits=12,
                verbose_name="Цена за единицу",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="material",
            name="unit",
            field=models.CharField(
                help_text="Например: «м³», «м²», «шт», «кг».",
                max_length=32,
                verbose_name="Единица измерения",
            ),
        ),
    ]
