# Generated by Django 5.2.6 on 2025-10-21 03:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_materials",
            "0003_remove_material_code_alter_material_is_active_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="supplier",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Название поставщика/контрагента (свободный ввод).",
                max_length=255,
                verbose_name="Поставщик",
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="vat_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Ставка НДС в процентах, например 12.00; оставьте пустым, если не задано.",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="НДС, %",
            ),
        ),
    ]
