# Generated by Django 5.2.6 on 2025-10-21 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_materials", "0004_material_supplier_material_vat_percent"),
        ("app_suppliers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="material",
            name="supplier",
        ),
        migrations.AddField(
            model_name="material",
            name="supplier_ref",
            field=models.ForeignKey(
                blank=True,
                help_text="Справочник поставщиков.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="materials",
                to="app_suppliers.supplier",
                verbose_name="Поставщик",
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="price_per_unit",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Текущая цена за 1 единицу измерения (живой справочник).",
                max_digits=12,
                verbose_name="Цена за единицу (без НДС)",
            ),
        ),
    ]
