# Generated by Django 5.2.6 on 2025-11-19 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantLogin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "login",
                    models.CharField(
                        help_text="Логин, который вводит пользователь на общей странице входа",
                        max_length=150,
                        unique=True,
                    ),
                ),
                (
                    "tenant_username",
                    models.CharField(
                        help_text="Имя пользователя внутри tenant-схемы", max_length=150
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_accounts",
                        to="app_tenants.domain",
                    ),
                ),
            ],
            options={
                "verbose_name": "Кросс-tenant аккаунт",
                "verbose_name_plural": "Кросс-tenant аккаунты",
            },
        ),
    ]
