# Generated by Django 5.2.6 on 2025-11-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_tenants", "0002_tenantlogin"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantLoginTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=96, unique=True)),
                ("schema_name", models.CharField(max_length=63)),
                ("tenant_username", models.CharField(max_length=150)),
                ("backend_path", models.CharField(max_length=255)),
                ("redirect_to", models.CharField(default="/ru/admin/", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "SSO-токен входа",
                "verbose_name_plural": "SSO-токены входа",
            },
        ),
    ]
