# Generated by Django 5.2.6 on 2025-11-05 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_materials", "0001_initial"),
        ("app_units", "0001_initial"),
        ("app_works", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TechnicalCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Название"
                    ),
                ),
                (
                    "materials_markup_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Например, 15.50 для 15.5%",
                        max_digits=5,
                        verbose_name="Надбавка на материалы (%)",
                    ),
                ),
                (
                    "works_markup_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Например, 20.00 для 20%",
                        max_digits=5,
                        verbose_name="Надбавка на работы (%)",
                    ),
                ),
                (
                    "transport_costs_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Применяется к чистой себестоимости материалов и работ (до надбавок)",
                        max_digits=5,
                        verbose_name="Транспортные расходы (%)",
                    ),
                ),
                (
                    "materials_margin_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Применяется к общей стоимости материалов",
                        max_digits=5,
                        verbose_name="Маржинальность материалов (%)",
                    ),
                ),
                (
                    "works_margin_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Применяется к общей стоимости работ",
                        max_digits=5,
                        verbose_name="Маржинальность работ (%)",
                    ),
                ),
                (
                    "unit_ref",
                    models.ForeignKey(
                        help_text="Выберите из справочника",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="technicalcards",
                        to="app_units.unit",
                        verbose_name="Единица измерения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Техкарта",
                "verbose_name_plural": "Техкарты",
            },
        ),
        migrations.CreateModel(
            name="TechnicalCardVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="Генерируется автоматически при создании",
                        max_length=64,
                        verbose_name="Версия",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликована"),
                ),
                (
                    "materials_markup_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Надбавка на материалы (%)",
                    ),
                ),
                (
                    "works_markup_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Надбавка на работы (%)",
                    ),
                ),
                (
                    "transport_costs_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Транспортные расходы (%)",
                    ),
                ),
                (
                    "materials_margin_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Маржинальность материалов (%)",
                    ),
                ),
                (
                    "works_margin_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Маржинальность работ (%)",
                    ),
                ),
                (
                    "materials_cost_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Себестоимость материалов за ед.",
                    ),
                ),
                (
                    "works_cost_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Себестоимость работ за ед.",
                    ),
                ),
                (
                    "total_cost_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Общая себестоимость за ед.",
                    ),
                ),
                (
                    "materials_total_cost_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="С учетом надбавок и транспорта",
                        max_digits=14,
                        verbose_name="Общая стоимость материалов за ед.",
                    ),
                ),
                (
                    "works_total_cost_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="С учетом надбавок и транспорта",
                        max_digits=14,
                        verbose_name="Общая стоимость работ за ед.",
                    ),
                ),
                (
                    "total_cost_with_markups_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Материалы + работы с надбавками и транспортом",
                        max_digits=14,
                        verbose_name="Общая стоимость техкарты за ед.",
                    ),
                ),
                (
                    "materials_sale_price_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="С учетом маржинальности",
                        max_digits=14,
                        verbose_name="Цена продажи материалов за ед.",
                    ),
                ),
                (
                    "works_sale_price_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="С учетом маржинальности",
                        max_digits=14,
                        verbose_name="Цена продажи работ за ед.",
                    ),
                ),
                (
                    "total_sale_price_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Итоговая цена продажи",
                        max_digits=14,
                        verbose_name="Цена продажи техкарты за ед.",
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="app_technical_cards.technicalcard",
                        verbose_name="Техкарта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Версия техкарты",
                "verbose_name_plural": "Версии техкарт",
                "ordering": ["card_id", "-created_at"],
                "unique_together": {("card", "version")},
            },
        ),
        migrations.CreateModel(
            name="TechnicalCardVersionMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_name",
                    models.CharField(
                        editable=False,
                        help_text="Заполняется автоматически",
                        max_length=255,
                        verbose_name="Название (снапшот)",
                    ),
                ),
                (
                    "price_per_unit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        editable=False,
                        max_digits=12,
                        null=True,
                        verbose_name="Цена за ед. (снапшот)",
                    ),
                ),
                (
                    "qty_per_unit",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        max_digits=16,
                        verbose_name="Количество на 1 ед. выпуска",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Порядок"
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        help_text="Выберите материал из справочника",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="app_materials.material",
                        verbose_name="Материал",
                    ),
                ),
                (
                    "technical_card_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_items",
                        to="app_technical_cards.technicalcardversion",
                        verbose_name="Версия ТК",
                    ),
                ),
                (
                    "unit_ref",
                    models.ForeignKey(
                        help_text="Выберите из справочника",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tecnicalcardversmaterials",
                        to="app_units.unit",
                        verbose_name="Единица измерения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Материал версии ТК",
                "verbose_name_plural": "Материалы версии ТК",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="TechnicalCardVersionWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "work_name",
                    models.CharField(
                        editable=False,
                        help_text="Заполняется автоматически",
                        max_length=255,
                        verbose_name="Название (снапшот)",
                    ),
                ),
                (
                    "price_per_unit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        editable=False,
                        max_digits=12,
                        null=True,
                        verbose_name="Цена за ед. (снапшот)",
                    ),
                ),
                (
                    "qty_per_unit",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        max_digits=16,
                        verbose_name="Количество на 1 ед. выпуска",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Порядок"
                    ),
                ),
                (
                    "technical_card_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_items",
                        to="app_technical_cards.technicalcardversion",
                        verbose_name="Версия ТК",
                    ),
                ),
                (
                    "unit_ref",
                    models.ForeignKey(
                        help_text="Выберите из справочника",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tecnicalcardversworks",
                        to="app_units.unit",
                        verbose_name="Единица измерения",
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        help_text="Выберите работу из справочника",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="app_works.work",
                        verbose_name="Работа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Работа версии ТК",
                "verbose_name_plural": "Работы версии ТК",
                "ordering": ["order", "id"],
            },
        ),
    ]
