# Generated by Django 5.2.6 on 2025-09-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_technical_cards", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="technicalcardversion",
            options={
                "ordering": ["card_id", "-version"],
                "verbose_name": "Версия техкарты",
                "verbose_name_plural": "Версии техкарт",
            },
        ),
        migrations.AlterModelOptions(
            name="technicalcardversionmaterial",
            options={
                "ordering": ["order", "id"],
                "verbose_name": "Материал версии ТК",
                "verbose_name_plural": "Материалы версии ТК",
            },
        ),
        migrations.AlterModelOptions(
            name="technicalcardversionwork",
            options={
                "ordering": ["order", "id"],
                "verbose_name": "Работа версии ТК",
                "verbose_name_plural": "Работы версии ТК",
            },
        ),
        migrations.AddField(
            model_name="technicalcard",
            name="code",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="technicalcard",
            name="output_unit",
            field=models.CharField(
                blank=True,
                default="",
                help_text="ед. выпуска ТК (напр. 'м', 'м2')",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="technicalcardversion",
            name="materials_cost_per_unit",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="technicalcardversion",
            name="output_unit",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="technicalcardversion",
            name="total_cost_per_unit",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="technicalcardversion",
            name="works_cost_per_unit",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="technicalcardversionmaterial",
            name="price_per_unit",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="technicalcardversionmaterial",
            name="qty_per_unit",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name="technicalcardversionmaterial",
            name="unit",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="technicalcardversionwork",
            name="price_per_unit",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="technicalcardversionwork",
            name="qty_per_unit",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name="technicalcardversionwork",
            name="unit",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
