# Generated by Django 5.2.6 on 2025-11-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_technical_cards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="technicalcardversionwork",
            name="calculation_method",
            field=models.CharField(
                choices=[("service", "Услуга"), ("labor", "Человеко-часы")],
                default="service",
                help_text="По какому методу фиксируем стоимость этой работы.",
                max_length=16,
                verbose_name="Метод расчёта",
            ),
        ),
    ]
