# Generated by Django 5.2.6 on 2025-11-17 15:38

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_technical_cards", "0002_technicalcardversionwork_calculation_method"),
        ("app_units", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="technicalcard",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"],
                name="technicalcard_name_trgm",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
