# Generated by Django 5.2.6 on 2025-10-02 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_materials", "0002_material_code_material_is_active_and_more"),
        ("app_technical_cards", "0002_alter_technicalcardversion_options_and_more"),
        ("app_works", "0002_work_code_work_is_active_work_price_per_unit_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="technicalcard",
            options={"verbose_name": "Техкарта", "verbose_name_plural": "Техкарты"},
        ),
        migrations.AlterModelOptions(
            name="technicalcardversion",
            options={
                "ordering": ["card_id", "-created_at"],
                "verbose_name": "Версия техкарты",
                "verbose_name_plural": "Версии техкарт",
            },
        ),
        migrations.RemoveField(
            model_name="technicalcard",
            name="code",
        ),
        migrations.RemoveField(
            model_name="technicalcardversion",
            name="name",
        ),
        migrations.RemoveField(
            model_name="technicalcardversion",
            name="output_unit",
        ),
        migrations.AlterField(
            model_name="technicalcard",
            name="name",
            field=models.CharField(
                db_index=True, max_length=255, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="technicalcard",
            name="output_unit",
            field=models.CharField(
                blank=True,
                default="",
                help_text="ед. выпуска ТК (напр. 'м', 'м2')",
                max_length=32,
                verbose_name="Ед. выпуска",
            ),
        ),
        migrations.AlterField(
            model_name="technicalcardversion",
            name="card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="app_technical_cards.technicalcard",
                verbose_name="Техкарта",
            ),
        ),
        migrations.AlterField(
            model_name="technicalcardversion",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="technicalcardversion",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Опубликована"),
        ),
        migrations.AlterField(
            model_name="technicalcardversion",
            name="materials_cost_per_unit",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=14,
                verbose_name="Стоимость материалов за ед.",
            ),
        ),
        migrations.AlterField(
            model_name="technicalcardversion",
            name="total_cost_per_unit",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=14,
                verbose_name="Общая стоимость за ед.",
            ),
        ),
        migrations.AlterField(
            model_name="technicalcardversion",
            name="version",
            field=models.CharField(
                help_text="Генерируется автоматически при создании",
                max_length=64,
                verbose_name="Версия",
            ),
        ),
        migrations.AlterField(
            model_name="technicalcardversion",
            name="works_cost_per_unit",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=14,
                verbose_name="Стоимость работ за ед.",
            ),
        ),
        migrations.AlterField(
            model_name="technicalcardversionmaterial",
            name="material",
            field=models.ForeignKey(
                default=1,
                help_text="Выберите материал из справочника",
                on_delete=django.db.models.deletion.PROTECT,
                to="app_materials.material",
                verbose_name="Материал",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="technicalcardversionmaterial",
            name="material_name",
            field=models.CharField(
                editable=False,
                help_text="Заполняется автоматически",
                max_length=255,
                verbose_name="Название (снапшот)",
            ),
        ),
        migrations.AlterField(
            model_name="technicalcardversionmaterial",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="Порядок"
            ),
        ),
        migrations.AlterField(
            model_name="technicalcardversionmaterial",
            name="price_per_unit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                editable=False,
                max_digits=12,
                null=True,
                verbose_name="Цена за ед. (снапшот)",
            ),
        ),
        migrations.AlterField(
            model_name="technicalcardversionmaterial",
            name="qty_per_unit",
            field=models.DecimalField(
                decimal_places=6,
                default=0,
                max_digits=16,
                verbose_name="Количество на 1 ед. выпуска",
            ),
        ),
        migrations.AlterField(
            model_name="technicalcardversionmaterial",
            name="technical_card_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="material_items",
                to="app_technical_cards.technicalcardversion",
                verbose_name="Версия ТК",
            ),
        ),
        migrations.AlterField(
            model_name="technicalcardversionmaterial",
            name="unit",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                max_length=32,
                verbose_name="Ед. изм. (снапшот)",
            ),
        ),
        migrations.AlterField(
            model_name="technicalcardversionwork",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="Порядок"
            ),
        ),
        migrations.AlterField(
            model_name="technicalcardversionwork",
            name="price_per_unit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                editable=False,
                max_digits=12,
                null=True,
                verbose_name="Цена за ед. (снапшот)",
            ),
        ),
        migrations.AlterField(
            model_name="technicalcardversionwork",
            name="qty_per_unit",
            field=models.DecimalField(
                decimal_places=6,
                default=0,
                max_digits=16,
                verbose_name="Количество на 1 ед. выпуска",
            ),
        ),
        migrations.AlterField(
            model_name="technicalcardversionwork",
            name="technical_card_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="work_items",
                to="app_technical_cards.technicalcardversion",
                verbose_name="Версия ТК",
            ),
        ),
        migrations.AlterField(
            model_name="technicalcardversionwork",
            name="unit",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                max_length=32,
                verbose_name="Ед. изм. (снапшот)",
            ),
        ),
        migrations.AlterField(
            model_name="technicalcardversionwork",
            name="work",
            field=models.ForeignKey(
                default=1,
                help_text="Выберите работу из справочника",
                on_delete=django.db.models.deletion.PROTECT,
                to="app_works.work",
                verbose_name="Работа",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="technicalcardversionwork",
            name="work_name",
            field=models.CharField(
                editable=False,
                help_text="Заполняется автоматически",
                max_length=255,
                verbose_name="Название (снапшот)",
            ),
        ),
    ]
