# Generated by Django 5.2.6 on 2025-10-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_technical_cards", "0003_alter_technicalcard_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="technicalcard",
            name="materials_margin_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Применяется к общей стоимости материалов",
                max_digits=5,
                verbose_name="Маржинальность материалов (%)",
            ),
        ),
        migrations.AddField(
            model_name="technicalcard",
            name="materials_markup_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Например, 15.50 для 15.5%",
                max_digits=5,
                verbose_name="Надбавка на материалы (%)",
            ),
        ),
        migrations.AddField(
            model_name="technicalcard",
            name="transport_costs_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Применяется к материалам и работам после надбавок",
                max_digits=5,
                verbose_name="Транспортные расходы (%)",
            ),
        ),
        migrations.AddField(
            model_name="technicalcard",
            name="works_margin_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Применяется к общей стоимости работ",
                max_digits=5,
                verbose_name="Маржинальность работ (%)",
            ),
        ),
        migrations.AddField(
            model_name="technicalcard",
            name="works_markup_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Например, 20.00 для 20%",
                max_digits=5,
                verbose_name="Надбавка на работы (%)",
            ),
        ),
        migrations.AddField(
            model_name="technicalcardversion",
            name="materials_margin_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="Маржинальность материалов (%)",
            ),
        ),
        migrations.AddField(
            model_name="technicalcardversion",
            name="materials_markup_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="Надбавка на материалы (%)",
            ),
        ),
        migrations.AddField(
            model_name="technicalcardversion",
            name="materials_sale_price_per_unit",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="С учетом маржинальности",
                max_digits=14,
                verbose_name="Цена продажи материалов за ед.",
            ),
        ),
        migrations.AddField(
            model_name="technicalcardversion",
            name="materials_total_cost_per_unit",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="С учетом надбавок и транспорта",
                max_digits=14,
                verbose_name="Общая стоимость материалов за ед.",
            ),
        ),
        migrations.AddField(
            model_name="technicalcardversion",
            name="total_cost_with_markups_per_unit",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Материалы + работы с надбавками и транспортом",
                max_digits=14,
                verbose_name="Общая стоимость техкарты за ед.",
            ),
        ),
        migrations.AddField(
            model_name="technicalcardversion",
            name="total_sale_price_per_unit",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Итоговая цена продажи",
                max_digits=14,
                verbose_name="Цена продажи техкарты за ед.",
            ),
        ),
        migrations.AddField(
            model_name="technicalcardversion",
            name="transport_costs_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="Транспортные расходы (%)",
            ),
        ),
        migrations.AddField(
            model_name="technicalcardversion",
            name="works_margin_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="Маржинальность работ (%)",
            ),
        ),
        migrations.AddField(
            model_name="technicalcardversion",
            name="works_markup_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="Надбавка на работы (%)",
            ),
        ),
        migrations.AddField(
            model_name="technicalcardversion",
            name="works_sale_price_per_unit",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="С учетом маржинальности",
                max_digits=14,
                verbose_name="Цена продажи работ за ед.",
            ),
        ),
        migrations.AddField(
            model_name="technicalcardversion",
            name="works_total_cost_per_unit",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="С учетом надбавок и транспорта",
                max_digits=14,
                verbose_name="Общая стоимость работ за ед.",
            ),
        ),
        migrations.AlterField(
            model_name="technicalcardversion",
            name="materials_cost_per_unit",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=14,
                verbose_name="Себестоимость материалов за ед.",
            ),
        ),
        migrations.AlterField(
            model_name="technicalcardversion",
            name="total_cost_per_unit",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=14,
                verbose_name="Общая себестоимость за ед.",
            ),
        ),
        migrations.AlterField(
            model_name="technicalcardversion",
            name="works_cost_per_unit",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=14,
                verbose_name="Себестоимость работ за ед.",
            ),
        ),
    ]
