# Generated by Django 5.2.6 on 2025-10-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_technical_cards", "0004_technicalcard_materials_margin_percent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technicalcard",
            name="transport_costs_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Применяется к чистой себестоимости материалов и работ (до надбавок)",
                max_digits=5,
                verbose_name="Транспортные расходы (%)",
            ),
        ),
    ]
