# Generated by Django 5.2.6 on 2025-10-22 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_technical_cards", "0005_alter_technicalcard_transport_costs_percent"),
        ("app_units", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="technicalcard",
            name="output_unit",
        ),
        migrations.RemoveField(
            model_name="technicalcardversionmaterial",
            name="unit",
        ),
        migrations.RemoveField(
            model_name="technicalcardversionwork",
            name="unit",
        ),
        migrations.AddField(
            model_name="technicalcard",
            name="unit_ref",
            field=models.ForeignKey(
                default=1,
                help_text="Выбирите из справочника",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="technicalcards",
                to="app_units.unit",
                verbose_name="Единица измерения",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="technicalcardversionmaterial",
            name="unit_ref",
            field=models.ForeignKey(
                default=1,
                help_text="Выбирите из справочника",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tecnicalcardversmaterials",
                to="app_units.unit",
                verbose_name="Единица измерения",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="technicalcardversionwork",
            name="unit_ref",
            field=models.ForeignKey(
                default=1,
                help_text="Выбирите из справочника",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tecnicalcardversworks",
                to="app_units.unit",
                verbose_name="Единица измерения",
            ),
            preserve_default=False,
        ),
    ]
