# Generated by Django 5.2.6 on 2025-10-23 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_technical_cards", "0006_remove_technicalcard_output_unit_and_more"),
        ("app_units", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technicalcard",
            name="unit_ref",
            field=models.ForeignKey(
                help_text="Выберите из справочника",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="technicalcards",
                to="app_units.unit",
                verbose_name="Единица измерения",
            ),
        ),
        migrations.AlterField(
            model_name="technicalcardversionmaterial",
            name="unit_ref",
            field=models.ForeignKey(
                help_text="Выберите из справочника",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tecnicalcardversmaterials",
                to="app_units.unit",
                verbose_name="Единица измерения",
            ),
        ),
        migrations.AlterField(
            model_name="technicalcardversionwork",
            name="unit_ref",
            field=models.ForeignKey(
                help_text="Выберите из справочника",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tecnicalcardversworks",
                to="app_units.unit",
                verbose_name="Единица измерения",
            ),
        ),
    ]
