# Generated by Django 5.2.6 on 2025-11-05 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_estimate_imports", "0001_initial"),
        ("app_overhead_costs", "0001_initial"),
        ("app_technical_cards", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Estimate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Короткое наименование сметы (как будет отображаться в списках и заголовках).",
                        max_length=255,
                        verbose_name="Название сметы",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        default="RUB",
                        help_text="Буквенный код валюты (ISO 4217), например: RUB, KZT, USD.",
                        max_length=8,
                        verbose_name="Валюта сметы",
                    ),
                ),
                (
                    "source_sheet_index",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        help_text="Номер листа Excel, по которому строилось превью (0 — первый лист).",
                        null=True,
                        verbose_name="Индекс листа Excel",
                    ),
                ),
                (
                    "settings_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Произвольные настройки сметы в формате JSON (ключ: значение).",
                        verbose_name="Настройки сметы",
                    ),
                ),
                (
                    "source_file",
                    models.ForeignKey(
                        blank=True,
                        help_text="От какого импортированного файла построена смета (для превью/трассировки).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="derived_estimates",
                        to="app_estimate_imports.importedestimatefile",
                        verbose_name="Источник (импортированный файл)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Смета",
                "verbose_name_plural": "Сметы",
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Отображаемое название раздела/группы в смете.",
                        max_length=255,
                        verbose_name="Название группы",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Порядок сортировки групп внутри одной сметы/родителя (меньше — выше).",
                        verbose_name="Порядок",
                    ),
                ),
                (
                    "estimate",
                    models.ForeignKey(
                        help_text="К какой смете относится данная группа/раздел.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="app_outlay.estimate",
                        verbose_name="Смета",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Если указано — группа будет вложенной (дочерней) относительно родительской.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="app_outlay.group",
                        verbose_name="Родительская группа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Группа сметы",
                "verbose_name_plural": "Группы сметы",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="GroupTechnicalCardLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=1,
                        help_text="Сколько единиц выпуска ТК требуется по смете (в единицах output_unit версии ТК).",
                        max_digits=16,
                        verbose_name="Количество выпуска",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Порядок сортировки ТК внутри группы (меньше — выше).",
                        verbose_name="Порядок",
                    ),
                ),
                (
                    "pinned_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Когда именно версия ТК была зафиксирована (связь добавлена в смету).",
                        verbose_name="Дата фиксации версии",
                    ),
                ),
                (
                    "source_row_index",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Номер строки в исходном Excel файле (для трассировки сопоставлений).",
                        null=True,
                        verbose_name="Индекс строки в источнике",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        help_text="Раздел/группа сметы, к которой привязывается версия технической карты.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="techcard_links",
                        to="app_outlay.group",
                        verbose_name="Группа сметы",
                    ),
                ),
                (
                    "technical_card_version",
                    models.ForeignKey(
                        help_text="Зафиксированная версия ТК, используемая в расчётах сметы.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="group_links",
                        to="app_technical_cards.technicalcardversion",
                        verbose_name="Версия технической карты",
                    ),
                ),
            ],
            options={
                "verbose_name": "ТК в группе сметы",
                "verbose_name_plural": "ТК в группах сметы",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="EstimateOverheadCostLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Порядок применения накладных расходов (если важна последовательность).",
                        verbose_name="Порядок применения",
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Когда контейнер был добавлен к смете.",
                        verbose_name="Дата применения",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Неактивные связи не учитываются в расчётах.",
                        verbose_name="Активен",
                    ),
                ),
                (
                    "snapshot_total_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Общая сумма накладных расходов на момент применения.",
                        max_digits=16,
                        null=True,
                        verbose_name="Сумма НР (снапшот)",
                    ),
                ),
                (
                    "snapshot_materials_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Процент на материалы на момент применения.",
                        max_digits=5,
                        null=True,
                        verbose_name="% на материалы (снапшот)",
                    ),
                ),
                (
                    "snapshot_works_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Процент на работы на момент применения.",
                        max_digits=5,
                        null=True,
                        verbose_name="% на работы (снапшот)",
                    ),
                ),
                (
                    "estimate",
                    models.ForeignKey(
                        help_text="Смета, к которой применяются накладные расходы.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overhead_cost_links",
                        to="app_outlay.estimate",
                        verbose_name="Смета",
                    ),
                ),
                (
                    "overhead_cost_container",
                    models.ForeignKey(
                        help_text="Контейнер накладных расходов, применяемый к смете.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="estimate_links",
                        to="app_overhead_costs.overheadcostcontainer",
                        verbose_name="Контейнер накладных расходов",
                    ),
                ),
            ],
            options={
                "verbose_name": "Накладные расходы в смете",
                "verbose_name_plural": "Накладные расходы в сметах",
                "ordering": ["order", "id"],
                "indexes": [
                    models.Index(
                        fields=["estimate", "order"],
                        name="app_outlay__estimat_123939_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="group",
            index=models.Index(
                fields=["estimate", "order"], name="app_outlay__estimat_05874f_idx"
            ),
        ),
    ]
