# Generated by Django 5.2.6 on 2025-09-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_outlay", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="group",
            options={
                "ordering": ["order", "id"],
                "verbose_name": "Группа сметы",
                "verbose_name_plural": "Группы сметы",
            },
        ),
        migrations.AlterModelOptions(
            name="grouptechnicalcardlink",
            options={
                "ordering": ["order", "id"],
                "verbose_name": "ТК в группе сметы",
                "verbose_name_plural": "ТК в группах сметы",
            },
        ),
        migrations.AddField(
            model_name="estimate",
            name="currency",
            field=models.CharField(blank=True, default="RUB", max_length=8),
        ),
        migrations.AddField(
            model_name="grouptechnicalcardlink",
            name="quantity",
            field=models.DecimalField(decimal_places=3, default=1, max_digits=16),
        ),
    ]
