# Generated by Django 5.2.6 on 2025-09-29 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_estimate_imports", "0002_parsemarkup"),
        ("app_outlay", "0002_alter_group_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="estimate",
            name="source_file",
            field=models.ForeignKey(
                blank=True,
                help_text="От какого импортированного файла построена смета (для превью).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derived_estimates",
                to="app_estimate_imports.importedestimatefile",
            ),
        ),
        migrations.AddField(
            model_name="estimate",
            name="source_sheet_index",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="Индекс листа Excel, по которому строилось превью.",
                null=True,
            ),
        ),
    ]
