# Generated by Django 5.2.6 on 2025-10-06 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_outlay", "0005_alter_estimate_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="grouptechnicalcardlink",
            unique_together=set(),
        ),
    ]
