# Generated by Django 5.2.6 on 2025-10-07 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_outlay", "0006_alter_grouptechnicalcardlink_unique_together"),
        ("app_overhead_costs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EstimateOverheadCostLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Порядок применения накладных расходов (если важна последовательность).",
                        verbose_name="Порядок применения",
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Когда контейнер был добавлен к смете.",
                        verbose_name="Дата применения",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Неактивные связи не учитываются в расчётах.",
                        verbose_name="Активен",
                    ),
                ),
                (
                    "snapshot_total_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Общая сумма накладных расходов на момент применения.",
                        max_digits=16,
                        null=True,
                        verbose_name="Сумма НР (снапшот)",
                    ),
                ),
                (
                    "snapshot_materials_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Процент на материалы на момент применения.",
                        max_digits=5,
                        null=True,
                        verbose_name="% на материалы (снапшот)",
                    ),
                ),
                (
                    "snapshot_works_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Процент на работы на момент применения.",
                        max_digits=5,
                        null=True,
                        verbose_name="% на работы (снапшот)",
                    ),
                ),
                (
                    "estimate",
                    models.ForeignKey(
                        help_text="Смета, к которой применяются накладные расходы.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overhead_cost_links",
                        to="app_outlay.estimate",
                        verbose_name="Смета",
                    ),
                ),
                (
                    "overhead_cost_container",
                    models.ForeignKey(
                        help_text="Контейнер накладных расходов, применяемый к смете.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="estimate_links",
                        to="app_overhead_costs.overheadcostcontainer",
                        verbose_name="Контейнер накладных расходов",
                    ),
                ),
            ],
            options={
                "verbose_name": "Накладные расходы в смете",
                "verbose_name_plural": "Накладные расходы в сметах",
                "ordering": ["order", "id"],
                "indexes": [
                    models.Index(
                        fields=["estimate", "order"],
                        name="app_outlay__estimat_123939_idx",
                    )
                ],
            },
        ),
    ]
