# Generated by Django 5.2.6 on 2025-10-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_outlay", "0007_estimateoverheadcostlink"),
    ]

    operations = [
        migrations.AddField(
            model_name="estimate",
            name="settings_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Произвольные настройки сметы в формате JSON (ключ: значение).",
                verbose_name="Настройки сметы",
            ),
        ),
    ]
