# Generated by Django 5.2.6 on 2025-11-05 10:12

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models

import app_estimate_imports.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImportedEstimateFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Оригинальный файл сметы, загруженный пользователем.",
                        upload_to=app_estimate_imports.models.upload_to_estimates,
                        verbose_name="Файл Excel",
                    ),
                ),
                (
                    "original_name",
                    models.CharField(
                        help_text="Имя файла на стороне пользователя (как было при загрузке).",
                        max_length=255,
                        verbose_name="Оригинальное имя файла",
                    ),
                ),
                (
                    "sha256",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Контрольная сумма для дедупликации и проверки целостности.",
                        max_length=64,
                        verbose_name="SHA-256",
                    ),
                ),
                (
                    "size_bytes",
                    models.BigIntegerField(
                        default=0,
                        help_text="Размер исходного файла в байтах.",
                        verbose_name="Размер, байт",
                    ),
                ),
                (
                    "sheet_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Сколько листов обнаружено в Excel-документе.",
                        verbose_name="Количество листов",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата и время загрузки файла.",
                        verbose_name="Загружено",
                    ),
                ),
            ],
            options={
                "verbose_name": "Импортированный файл сметы",
                "verbose_name_plural": "Импортированные файлы смет",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ParseResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        help_text="Универсальный JSON-слепок, полученный из Excel (JSONB в Postgres).",
                        verbose_name="Данные парсинга",
                    ),
                ),
                (
                    "estimate_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Имя/заголовок сметы, извлечённый из данных (если найден).",
                        max_length=255,
                        verbose_name="Название сметы",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата и время формирования результата парсинга.",
                        verbose_name="Создано",
                    ),
                ),
                (
                    "file",
                    models.OneToOneField(
                        help_text="Файл, к которому относится данный результат парсинга.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parse_result",
                        to="app_estimate_imports.importedestimatefile",
                        verbose_name="Файл",
                    ),
                ),
            ],
            options={
                "verbose_name": "Результат парсинга",
                "verbose_name_plural": "Результаты парсинга",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ParseMarkup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "annotation",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON-структура разметки: роли узлов и связи техкарт с работами и материалами (ключи — UID из данных парсинга).",
                        verbose_name="Аннотация",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Дата и время последнего изменения разметки.",
                        verbose_name="Обновлено",
                    ),
                ),
                (
                    "file",
                    models.OneToOneField(
                        help_text="Файл-источник, для которого выполняется разметка.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="markup",
                        to="app_estimate_imports.importedestimatefile",
                        verbose_name="Файл",
                    ),
                ),
                (
                    "parse_result",
                    models.OneToOneField(
                        help_text="Конкретный результат парсинга, на основе которого делается разметка.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="markup",
                        to="app_estimate_imports.parseresult",
                        verbose_name="Результат парсинга",
                    ),
                ),
            ],
            options={
                "verbose_name": "Разметка сметы",
                "verbose_name_plural": "Разметки смет",
            },
        ),
        migrations.AddIndex(
            model_name="parseresult",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["data"], name="parse_result_data_gin"
            ),
        ),
    ]
