# Generated by Django 5.2.6 on 2025-09-23 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_estimate_imports", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParseMarkup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("annotation", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="markup",
                        to="app_estimate_imports.importedestimatefile",
                    ),
                ),
                (
                    "parse_result",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="markup",
                        to="app_estimate_imports.parseresult",
                    ),
                ),
            ],
            options={
                "verbose_name": "Разметка сметы",
                "verbose_name_plural": "Разметки смет",
            },
        ),
    ]
