# Generated by Django 5.2.6 on 2025-10-20 08:12

import app_estimate_imports.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_estimate_imports", "0002_parsemarkup"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="importedestimatefile",
            options={
                "ordering": ["-uploaded_at"],
                "verbose_name": "Импортированный файл сметы",
                "verbose_name_plural": "Импортированные файлы смет",
            },
        ),
        migrations.AlterModelOptions(
            name="parseresult",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Результат парсинга",
                "verbose_name_plural": "Результаты парсинга",
            },
        ),
        migrations.AlterField(
            model_name="importedestimatefile",
            name="file",
            field=models.FileField(
                help_text="Оригинальный файл сметы, загруженный пользователем.",
                upload_to=app_estimate_imports.models.upload_to_estimates,
                verbose_name="Файл Excel",
            ),
        ),
        migrations.AlterField(
            model_name="importedestimatefile",
            name="original_name",
            field=models.CharField(
                help_text="Имя файла на стороне пользователя (как было при загрузке).",
                max_length=255,
                verbose_name="Оригинальное имя файла",
            ),
        ),
        migrations.AlterField(
            model_name="importedestimatefile",
            name="sha256",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Контрольная сумма для дедупликации и проверки целостности.",
                max_length=64,
                verbose_name="SHA-256",
            ),
        ),
        migrations.AlterField(
            model_name="importedestimatefile",
            name="sheet_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Сколько листов обнаружено в Excel-документе.",
                verbose_name="Количество листов",
            ),
        ),
        migrations.AlterField(
            model_name="importedestimatefile",
            name="size_bytes",
            field=models.BigIntegerField(
                default=0,
                help_text="Размер исходного файла в байтах.",
                verbose_name="Размер, байт",
            ),
        ),
        migrations.AlterField(
            model_name="importedestimatefile",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Дата и время загрузки файла.",
                verbose_name="Загружено",
            ),
        ),
        migrations.AlterField(
            model_name="parsemarkup",
            name="annotation",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSON-структура разметки: роли узлов и связи техкарт с работами и материалами (ключи — UID из данных парсинга).",
                verbose_name="Аннотация",
            ),
        ),
        migrations.AlterField(
            model_name="parsemarkup",
            name="file",
            field=models.OneToOneField(
                help_text="Файл-источник, для которого выполняется разметка.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="markup",
                to="app_estimate_imports.importedestimatefile",
                verbose_name="Файл",
            ),
        ),
        migrations.AlterField(
            model_name="parsemarkup",
            name="parse_result",
            field=models.OneToOneField(
                help_text="Конкретный результат парсинга, на основе которого делается разметка.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="markup",
                to="app_estimate_imports.parseresult",
                verbose_name="Результат парсинга",
            ),
        ),
        migrations.AlterField(
            model_name="parsemarkup",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Дата и время последнего изменения разметки.",
                verbose_name="Обновлено",
            ),
        ),
        migrations.AlterField(
            model_name="parseresult",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Дата и время формирования результата парсинга.",
                verbose_name="Создано",
            ),
        ),
        migrations.AlterField(
            model_name="parseresult",
            name="data",
            field=models.JSONField(
                help_text="Универсальный JSON-слепок, полученный из Excel (JSONB в Postgres).",
                verbose_name="Данные парсинга",
            ),
        ),
        migrations.AlterField(
            model_name="parseresult",
            name="estimate_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Имя/заголовок сметы, извлечённый из данных (если найден).",
                max_length=255,
                verbose_name="Название сметы",
            ),
        ),
        migrations.AlterField(
            model_name="parseresult",
            name="file",
            field=models.OneToOneField(
                help_text="Файл, к которому относится данный результат парсинга.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parse_result",
                to="app_estimate_imports.importedestimatefile",
                verbose_name="Файл",
            ),
        ),
    ]
