# Generated by Django 5.2.6 on 2025-11-05 10:12

import django.core.validators
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Как принято называть поставщика в работе (для интерфейса).",
                        max_length=255,
                        verbose_name="Короткое название",
                    ),
                ),
                (
                    "legal_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Полное юридическое наименование, если отличается.",
                        max_length=255,
                        verbose_name="Юридическое наименование",
                    ),
                ),
                (
                    "supplier_type",
                    models.CharField(
                        choices=[
                            ("LEGAL", "Юрлицо"),
                            ("SOLE", "ИП"),
                            ("PERSON", "Физлицо"),
                        ],
                        default="LEGAL",
                        help_text="Юрлицо / ИП / Физлицо.",
                        max_length=12,
                        verbose_name="Тип поставщика",
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="12 цифр, если известен.",
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Должно быть 12 цифр.", regex="^\\d{12}$"
                            )
                        ],
                        verbose_name="БИН/ИИН",
                    ),
                ),
                (
                    "vat_registered",
                    models.BooleanField(
                        default=True,
                        help_text="Отметьте, если поставщик является плательщиком НДС.",
                        verbose_name="Плательщик НДС",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Контактный телефон.",
                        max_length=64,
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default="",
                        help_text="Рабочий e-mail.",
                        max_length=254,
                        verbose_name="E-mail",
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Сайт или страница с каталогом.",
                        verbose_name="Сайт",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Любая полезная информация: условия поставки, график и т.д.",
                        verbose_name="Заметки",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Снимите отметку, чтобы скрыть из выбора без удаления.",
                        verbose_name="Активен",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Поставщик",
                "verbose_name_plural": "Поставщики",
                "ordering": ["name", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"),
                        name="uniq_supplier_name_ci",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("tax_id", ""), _negated=True),
                        fields=("tax_id",),
                        name="uniq_supplier_tax_id_nonempty",
                    ),
                ],
            },
        ),
    ]
