# Generated by Django 5.2.6 on 2025-11-05 19:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_suppliers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="tax_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="10 цифр, если известен.",
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Должно быть 10 цифр.", regex="^\\d{10}$"
                    )
                ],
                verbose_name="ИНН",
            ),
        ),
    ]
