services:
  redis:
    image: redis:7-alpine
    container_name: redis_metiz
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - metiz_network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis_commander
    restart: unless-stopped
    environment:
      REDIS_HOSTS: local:redis_metiz:6379
    ports:
      - "8081:8081"
    networks:
      - metiz_network

networks:
  metiz_network:
    external: true
