# Generated by Django 5.2.6 on 2025-11-05 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_units", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Короткое понятное название работы.",
                        max_length=255,
                        verbose_name="Наименование работы",
                    ),
                ),
                (
                    "price_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Текущая стоимость за 1 единицу измерения (живой справочник).",
                        max_digits=12,
                        verbose_name="Расценка за единицу",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Снимите отметку, чтобы скрыть работу из выбора без удаления.",
                        verbose_name="Активна",
                    ),
                ),
                (
                    "unit_ref",
                    models.ForeignKey(
                        help_text="Выберите из справочника",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="works",
                        to="app_units.unit",
                        verbose_name="Единица измерения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Работа",
                "verbose_name_plural": "Работы",
                "ordering": ["name", "id"],
            },
        ),
    ]
