# Generated by Django 5.2.6 on 2025-09-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_works", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="code",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="work",
            name="price_per_unit",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="unit",
            field=models.CharField(
                blank=True,
                default="",
                help_text="ед. изм. (напр. 'чел·ч', 'м2')",
                max_length=32,
            ),
        ),
    ]
