# Generated by Django 5.2.6 on 2025-11-13 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_units", "0001_initial"),
        ("app_works", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="labor_unit_ref",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите единицу измерения для расчёта по человеко-часам.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="works_labor",
                to="app_units.unit",
                verbose_name="Единица человеко-часов",
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="price_per_labor_hour",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Стоимость работы за один человеко-час.",
                max_digits=12,
                null=True,
                verbose_name="Расценка за человеко-час",
            ),
        ),
    ]
