# Generated by Django 5.2.6 on 2025-11-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_works", "0002_work_labor_unit_ref_work_price_per_labor_hour"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="work",
            name="labor_unit_ref",
        ),
        migrations.AddField(
            model_name="work",
            name="calculate_only_by_labor",
            field=models.BooleanField(
                default=False,
                help_text="Если включено, работа всегда рассчитывается по тарифу за человеко-час.",
                verbose_name="Считать только по ЧЧ",
            ),
        ),
    ]
