# Generated by Django 5.2.6 on 2025-10-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_works", "0002_work_code_work_is_active_work_price_per_unit_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="work",
            name="code",
        ),
        migrations.AlterField(
            model_name="work",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Снимите отметку, чтобы скрыть работу из выбора без удаления.",
                verbose_name="Активна",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="Короткое понятное название работы.",
                max_length=255,
                verbose_name="Наименование работы",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="price_per_unit",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                help_text="Текущая стоимость за 1 единицу измерения (живой справочник).",
                max_digits=12,
                verbose_name="Расценка за единицу",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="work",
            name="unit",
            field=models.CharField(
                help_text="Например: «чел·ч», «м²», «п.м.».",
                max_length=32,
                verbose_name="Единица измерения",
            ),
        ),
    ]
