# Generated by Django 5.2.6 on 2025-11-19 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_suppliers",
            "0002_remove_supplier_uniq_supplier_tax_id_nonempty_and_more",
        ),
        ("app_works", "0003_remove_work_labor_unit_ref_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="supplier_ref",
            field=models.ForeignKey(
                blank=True,
                help_text="Справочник поставщиков.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="works",
                to="app_suppliers.supplier",
                verbose_name="Поставщик",
            ),
        ),
    ]
