# Generated by Django 5.2.6 on 2025-11-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_works", "0004_work_supplier_ref"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="labor_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Нормативное количество человеко-часов на единицу работы.",
                max_digits=12,
                verbose_name="Кол-во человеко-часов",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="price_per_labor_hour",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Стоимость работы за один человеко-час.",
                max_digits=12,
                null=True,
                verbose_name="Предварительная расценка за человеко-час",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="price_per_unit",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Текущая стоимость за 1 единицу измерения (живой справочник).",
                max_digits=12,
                verbose_name="Расценка за единицу",
            ),
        ),
    ]
