# Generated by Django 5.2.6 on 2025-11-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_works", "0005_work_labor_hours_alter_work_price_per_labor_hour_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="labor_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Нормативное количество человеко-часов на единицу работы.",
                max_digits=12,
                verbose_name="Кол-во человеко-часов",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="price_per_unit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Текущая стоимость за 1 единицу измерения (живой справочник).",
                max_digits=12,
                verbose_name="Расценка за единицу",
            ),
        ),
    ]
